package dto;

import javax.persistence.Id;

import inject.Dto;

@Dto
public class Code {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.code.kind
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    @Id
    private String kind;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.code.value
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    @Id
    private String value;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.code.label
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    private String label;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.code.description
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.code.sort_order
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.kind
     * @return  the value of public.code.kind
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.kind
     * @param kind  the value for public.code.kind
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public void setKind(final String kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.value
     * @return  the value of public.code.value
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.value
     * @param value  the value for public.code.value
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public void setValue(final String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.label
     * @return  the value of public.code.label
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.label
     * @param label  the value for public.code.label
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public void setLabel(final String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.description
     * @return  the value of public.code.description
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.description
     * @param description  the value for public.code.description
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.sort_order
     * @return  the value of public.code.sort_order
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.sort_order
     * @param sortOrder  the value for public.code.sort_order
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public enum Kind {
        ROLE,
    }
}