package dto;

import javax.persistence.Id;

import inject.Dto;

@Dto
public class Code {

    /**
     * Database Column Remarks: コード種別 This field was generated by MyBatis Generator. This field corresponds to the database column public.code.kind
     * @mbg.generated
     */
    private String kind;
    /**
     * Database Column Remarks: 値 This field was generated by MyBatis Generator. This field corresponds to the database column public.code.value
     * @mbg.generated
     */
    private String value;
    /**
     * Database Column Remarks: ラベル This field was generated by MyBatis Generator. This field corresponds to the database column public.code.label
     * @mbg.generated
     */
    private String label;
    /**
     * Database Column Remarks: 説明 This field was generated by MyBatis Generator. This field corresponds to the database column public.code.description
     * @mbg.generated
     */
    private String description;
    /**
     * Database Column Remarks: 順序 This field was generated by MyBatis Generator. This field corresponds to the database column public.code.sort_order
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.kind
     * @return  the value of public.code.kind
     * @mbg.generated
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.kind
     * @param kind  the value for public.code.kind
     * @mbg.generated
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.value
     * @return  the value of public.code.value
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.value
     * @param value  the value for public.code.value
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.label
     * @return  the value of public.code.label
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.label
     * @param label  the value for public.code.label
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.description
     * @return  the value of public.code.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.description
     * @param description  the value for public.code.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.code.sort_order
     * @return  the value of public.code.sort_order
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.code.sort_order
     * @param sortOrder  the value for public.code.sort_order
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public enum Kind {
        ROLE,
    }
}