package dto;

import javax.persistence.Id;

import inject.Dto;

@Dto
public class Role {

    /**
     * Database Column Remarks: Eメールアドレス This field was generated by MyBatis Generator. This field corresponds to the database column public.role.emailaddress
     * @mbg.generated
     */
    @Id
    private String emailaddress;
    /**
     * Database Column Remarks: ロール This field was generated by MyBatis Generator. This field corresponds to the database column public.role.role
     * @mbg.generated
     */
    @Id
    private String role;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.emailaddress
     * @return  the value of public.role.emailaddress
     * @mbg.generated
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.emailaddress
     * @param emailaddress  the value for public.role.emailaddress
     * @mbg.generated
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress == null ? null : emailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.role
     * @return  the value of public.role.role
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.role
     * @param role  the value for public.role.role
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    public Role() {
        // JPAでは、デフォルトコンストラクタが必須のため
    }

    public Role(final String emailaddress, final String role) {
        this.emailaddress = emailaddress;
        this.role = role;
    }
}