package dto;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.emailaddress
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    private String emailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.role.emailaddress
     *
     * @return the value of public.role.emailaddress
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.role.emailaddress
     *
     * @param emailaddress the value for public.role.emailaddress
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.role.role
     *
     * @return the value of public.role.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.role.role
     *
     * @param role the value for public.role.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    public void setRole(String role) {
        this.role = role;
    }
}