package dto;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

import inject.Dto;
import lombok.Getter;
import lombok.Setter;

@Dto
@XmlRootElement
public class User {

    /**
     * Database Column Remarks: Eメールアドレス This field was generated by MyBatis Generator. This field corresponds to the database column public.user.emailaddress
     * @mbg.generated
     */
    @Id
    private String emailaddress;
    /**
     * Database Column Remarks: 姓 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.last_name
     * @mbg.generated
     */
    @Column(name = "last_name")
    private String lastName;
    /**
     * Database Column Remarks: 名 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.first_name
     * @mbg.generated
     */
    @Column(name = "first_name")
    private String firstName;
    /**
     * Database Column Remarks: パスワード This field was generated by MyBatis Generator. This field corresponds to the database column public.user.password
     * @mbg.generated
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2020-04-12T12:59:05.835+09:00", comments = "Source field: USER.password")
    private String password;
    /**
     * Database Column Remarks: 郵便番号 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.postal_code
     * @mbg.generated
     */
    @Column(name = "postal_code")
    private String postalCode;
    /**
     * Database Column Remarks: 都道府県 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.region
     * @mbg.generated
     */
    private String region;
    /**
     * Database Column Remarks: 市区町村 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.locality
     * @mbg.generated
     */
    private String locality;
    /**
     * Database Column Remarks: 町域 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.street_address
     * @mbg.generated
     */
    @Column(name = "street_address")
    private String streetAddress;
    /**
     * Database Column Remarks: その他住所 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.extended_address
     * @mbg.generated
     */
    @Column(name = "extended_address")
    private String extendedAddress;
    /**
     * Database Column Remarks: バージョン This field was generated by MyBatis Generator. This field corresponds to the database column public.user.version
     * @mbg.generated
     */
    @Version
    private Integer version;
    /**
     * Database Column Remarks: 作成日時 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.createdtime
     * @mbg.generated
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2020-04-12T12:59:05.835+09:00", comments = "Source field: USER.createdTime")
    private LocalDateTime createdtime;
    /**
     * Database Column Remarks: 更新日時 This field was generated by MyBatis Generator. This field corresponds to the database column public.user.updatedtime
     * @mbg.generated
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2020-04-12T12:59:05.835+09:00", comments = "Source field: USER.updatedTime")
    private LocalDateTime updatedtime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.emailaddress
     * @return  the value of public.user.emailaddress
     * @mbg.generated
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.emailaddress
     * @param emailaddress  the value for public.user.emailaddress
     * @mbg.generated
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress == null ? null : emailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.last_name
     * @return  the value of public.user.last_name
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.last_name
     * @param lastName  the value for public.user.last_name
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.first_name
     * @return  the value of public.user.first_name
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.first_name
     * @param firstName  the value for public.user.first_name
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.password
     * @return  the value of public.user.password
     * @mbg.generated
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2020-04-12T12:59:05.835+09:00", comments = "Source field: USER.password")
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.password
     * @param password  the value for public.user.password
     * @mbg.generated
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2020-04-12T12:59:05.835+09:00", comments = "Source field: USER.password")
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.postal_code
     * @return  the value of public.user.postal_code
     * @mbg.generated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.postal_code
     * @param postalCode  the value for public.user.postal_code
     * @mbg.generated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.region
     * @return  the value of public.user.region
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.region
     * @param region  the value for public.user.region
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.locality
     * @return  the value of public.user.locality
     * @mbg.generated
     */
    public String getLocality() {
        return locality;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.locality
     * @param locality  the value for public.user.locality
     * @mbg.generated
     */
    public void setLocality(String locality) {
        this.locality = locality == null ? null : locality.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.street_address
     * @return  the value of public.user.street_address
     * @mbg.generated
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.street_address
     * @param streetAddress  the value for public.user.street_address
     * @mbg.generated
     */
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress == null ? null : streetAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.extended_address
     * @return  the value of public.user.extended_address
     * @mbg.generated
     */
    public String getExtendedAddress() {
        return extendedAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.extended_address
     * @param extendedAddress  the value for public.user.extended_address
     * @mbg.generated
     */
    public void setExtendedAddress(String extendedAddress) {
        this.extendedAddress = extendedAddress == null ? null : extendedAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.version
     * @return  the value of public.user.version
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.version
     * @param version  the value for public.user.version
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.createdtime
     * @return  the value of public.user.createdtime
     * @mbg.generated
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2020-04-12T12:59:05.835+09:00", comments = "Source field: USER.createdTime")
    public LocalDateTime getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.createdtime
     * @param createdtime  the value for public.user.createdtime
     * @mbg.generated
     */
    public void setCreatedtime(LocalDateTime createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.updatedtime
     * @return  the value of public.user.updatedtime
     * @mbg.generated
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", date = "2020-04-12T12:59:05.835+09:00", comments = "Source field: USER.updatedTime")
    public LocalDateTime getUpdatedtime() {
        return updatedtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.updatedtime
     * @param updatedtime  the value for public.user.updatedtime
     * @mbg.generated
     */
    public void setUpdatedtime(LocalDateTime updatedtime) {
        this.updatedtime = updatedtime;
    }

    @OneToMany(cascade = CascadeType.ALL) // Userを変更しただけで、Roleも自動で変更が反映される
    @JoinColumn(name = "emailaddress")
    @Getter
    @Setter
    private List<Role> roles;

}
