package mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import dto.Code;
import dto.CodeExample;

@Mapper
public interface CodeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    long countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);
}