package mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import dto.Code;
import dto.CodeExample;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CodeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    long countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("kind") String kind, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    List<Code> selectByExampleWithRowbounds(CodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    Code selectByPrimaryKey(@Param("kind") String kind, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Code record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.code
     * @mbg.generated
     */
    int updateByPrimaryKey(Code record);
}