package mapper;

import dto.Role;
import dto.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role
     *
     * @mbg.generated Fri May 01 10:38:34 JST 2020
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);
}