package mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import dto.Role;
import dto.RoleExample;

@Mapper
public interface RoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
     * @mbg.generated  Sat Aug 01 16:58:00 JST 2020
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);
}