package mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import dto.User;
import dto.UserExample;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int deleteByPrimaryKey(String emailaddress);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    User selectByPrimaryKey(String emailaddress);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
}